### ISSUE TITLE
Gun effect

### ISSUE THREAD

**Issue by Magpieeeeeee** [walmis/VPforce-TelemFFB#2]
I have no idea how to program this
But would it be possible to make the gun effect go 45 degrees
And for the next instance go 225 degrees

it was cool to turn it up on the a10 but it ends with your aim tracking up and to the right.
Maybe it would be easier to make it pulse 90, 180,270 and then 0 then repeat

**Comment by mjfrisby** [comment]
if you use the wip branch, there is the option to randomize the gunfire effect direction.  Setting the direction value to -1 in the config will result in the stick wandering around center during a pull of the trigger

**Comment by mjfrisby** [comment]
marking closed
