### ISSUE TITLE
Clear setting button moves layout

### ISSUE THREAD

**Issue by RoyMudie** [walmis/VPforce-TelemFFB#23]
Modifying a setting adds the "clear settings" button to the right hand side. However, because this button is added and removed to the interface, rather than hidden/shown, the interface moves which is a little distracting.

Suggest that the buttons are setVisible(False) / setVisible(True) rather than the widget physically removed/added.

**Comment by mjfrisby** [comment]
this is a tricky one since a "not visible" widget is equivalent to a non-existent widget in terms of layouts.

was able to leverage style sheets (to set transparent color) and hide the pixmap icon when the button is "disabled", so it appears to be gone.
