### ISSUE TITLE
Loading Application depending on the current aircraft

### ISSUE THREAD

**Issue by LtJaeger** [walmis/VPforce-TelemFFB#28]
It would be great if the app could run batch files or start applications with parameters, depending on the current aircraft.
Stopping / killing apps would also be great.

Use case :
I use joystick gremlin. The app is launched with DCS. I got certain profiles which would run e.g. only with the VKB F-14 grip and the F-14 Module . If I change grips, it will produce a error message. I need to manually change the profile to suit the current stick and airplane other than the mentioned Modul due to the need for a different profile. 
Idea is, Telem start/stops the app and with a modifier (per app) pending on the choose plane, like it loading a specific rhino profile. 

If not possible it would be nice to run a batch file (

**Comment by mjfrisby** [comment]
Implemented in 137a699 and 7a1f66d
