### ISSUE TITLE
Crash when adding a row for "any" device in Settings Manager

### ISSUE THREAD

**Issue by RoyMudie** [walmis/VPforce-TelemFFB#30]
The application crashes when you add a row to the "any" list in the settings manager.

To replicate:
1) Select: System -> Edit Sim/Class Defaults & Offline Models from the menu
2) Change "Current Device" to "any"
3) Double click on an empty cell under "Source" (any column will cause the crash)
4) Enter a value (e.g. "blah")
5) Click away to "save" the value
6) Click on the row that you just entered "blah" in
7) CRASH

**Comment by mjfrisby** [comment]
thanks, this is a bug in the SM interface.  The cells should never be editable under any circumstance
