### ISSUE TITLE
Telemetry "Waiting for data" text includes game status, but this only changes on application restart

### ISSUE THREAD

**Issue by RoyMudie** [walmis/VPforce-TelemFFB#31]
As title. This creates a bad user experience because:
1) The information is unnecessary repeated (this is the same information as shown via the icons at the top of the screen)
2) The information isn't consistent

For a first time user this creates a bad user experience because they have:
1) Enabled a game via the System Settings popup shown on first load
2) Immediately been presented incorrect information
3) Immediately see conflicting information

![image](https://github.com/walmis/VPforce-TelemFFB/assets/5470814/9d75bac1-b170-4265-ba7d-99a30fc322cb)

![image](https://github.com/walmis/VPforce-TelemFFB/assets/5470814/95ccaab1-4e50-4e1d-b83b-1e7388f5c587)

**Comment by mjfrisby** [comment]
this already had a pending fix and will be included in the next update (commit id: aa16d13d)
