### ISSUE TITLE
System Settings window can be resized but layout doesn't flow

### ISSUE THREAD

**Issue by RoyMudie** [walmis/VPforce-TelemFFB#35]
Either the work needs to be done to make this a liquid layout or change the dialogue to be a fixed size.

![image](https://github.com/walmis/VPforce-TelemFFB/assets/5470814/89643590-e487-4193-ac16-474e76a0fdde)

![image](https://github.com/walmis/VPforce-TelemFFB/assets/5470814/2cc79e34-4769-4790-b08b-a6f93684fa9d)

**Comment by mjfrisby** [comment]
resolved per above commit
