### ISSUE TITLE
[Feature request] Make the "Override DCS Spring" effect kept on pause with "Keep forces on Pause/Slew" turned on

### ISSUE THREAD

**Issue by Havner** [walmis/VPforce-TelemFFB#51]
EDIT: I've read the tooltip (Make the damper/inertia/friction on with pause). It works as expected, but with the use case I described originally there is a case to be made to also include the spring overrides into "keep forces on pause".

Original message:

Tested on DCS: Mi-8

Set "Keep forces on Pause/Slew" to on.
Set "Damper effect" to on.
Set "Override DCS Spring" to on with 0%.

Fly without the trimmer (only on damper, spring 0%). Hit esc. Damper still on, but the spring returns to some other non overridden 0% value.

**Comment by mjfrisby** [comment]
I'll look at this, thanks
